{
 "title": "Contact Us Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage - Compressed Class Space",
   "type": "timeseries",
   "description": "How much compressed pointer memory the Contact Us Service application has left. The lines should never touch. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\", id=\"Compressed Class Space\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=\"Compressed Class Space\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "How much CPU is being used by the Contact Us Service application",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active HTTP Requests",
   "type": "timeseries",
   "description": "Number of active HTTP requests towards the Contact Us Service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Tasks Available",
   "type": "timeseries",
   "description": "When this hits 0%, the Contact Us Service will start rejecting ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "executor_queue_remaining_tasks", "legendFormat": "__auto" }
   ]
  }
 ]
}