global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "spring"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - "contactus-service.default.svc.cluster.local:8080"
        - "frontend-service.default.svc.cluster.local:4000"
        - "graphs-service.default.svc.cluster.local:8081"
