apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-contactus-service-deployment
  labels:
    app: gc-contactus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-contactus-service
  template:
    metadata:
      labels:
        app: gc-contactus-service
    spec:
      containers:
      - name: gc-contactus-service
        image: chrisstefaniak/gc-contactus-service:latest
        imagePullPolicy: Always 
        volumeMounts:
          - name: shared-logs
            mountPath: "/shared/logs"
        env:
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: sendgrid-api-key
                key: SENDGRID_API_KEY
          - name: ENV
            value: "prod"
        ports:
        - containerPort: 8080
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-logs-pvc
        