apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-frontend-deployment
  labels:
    app: gb-frontend324324234
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gb-frontend
  template:
    metadata:
      labels:
        app: gb-frontend
    spec:
      containers:
      - name: gb-frontend
        image: chrisstefaniak/gb-frontend:gb-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000