apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gb-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: graphcrafter.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - pathType: Prefix
        path: /creategraph
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - pathType: Prefix
        path: /savedgraphs
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - pathType: Prefix
        path: /about
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - pathType: Prefix
        path: /contact
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - pathType: Prefix
        path: /allgraphs
        backend:
          service:
            name: graphs-service
            port:
              number: 8081
      - pathType: Prefix
        path: /graphs
        backend:
          service:
            name: graphs-service
            port:
              number: 8081
      - pathType: Prefix
        path: /graphs/actuator/prometheus
        backend:
          service:
            name: graphs-service
            port:
              number: 8081
      - pathType: Prefix
        path: /contactus
        backend:
          service:
            name: contactus-service
            port:
              number: 8080
      - pathType: Prefix
        path: /contactus/actuator/prometheus
        backend:
          service:
            name: contactus-service
            port:
              number: 8080
  - host: metrics.graphcrafter.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: grafana
            port:
              number: 3000
  - host: elasticsearch.example.com # remove later
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: elasticsearch-master
            port:
              number: 9200